# Configurations that will apply to every benchmark.
common:
    # Defines if the garbage collector should be called before every benchmark.
    # Default value is true.
    gc: true

    # Folder containing the benchmark results.
    output-folder: /tmp

    # Number of times a single benchmark will be executed.
    iterations:
        # Number of non-recorded iterations of a benchmark. Used to warm up the JVM.
        # The warm-up iterations will not be run for benchmarks that doesn't benefit from it.
        # Default value is 5.
        warmup: 0

        # How many times a single benchmark will be executed.
        # Default value is 5.
        execution: 1

    # Configurations that apply only to time based benchmarks.
    time:
        # The time unit the results refer to.
        # Possible values are: SECONDS, MILLISECONDS, MICROSECONDS, NANOSECONDS
        # Default is NANOSECONDS. 
        unit: NANOSECONDS

        # Defines how the execution time is measured.
        # Possible values are: AverageTime, SampleTime, SingleShotTime, Throughput, ALL.
        # Default is AverageTime.
        # See org.openjdk.jmh.annotations.Mode for more details.
        mode: AverageTime

        # Number of seconds every warmup iteration should last.
        # Default value is 5.
        warmup: 5

        # Number of seconds every execution iteration should last.
        # Default value 5.
        execution: 5
    
    # Number of initial active nodes.
    # At least one positive value must be provided.
    # Benchmarks will run for every specified cluster size.
    # init-nodes: [10, 100, 1000, 10_000, 100_000]
    # init-nodes: [3,6,12,24,48,96,192,384,768,1536,3072,6144,12288,24576,49152,98304,196608,393216,786432]
    init-nodes: [
          1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
         21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
         41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
         61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
         81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99,100,
        101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,
        121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,
        141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,
        161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,
        181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,
        201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,
        221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,
        241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256
    ]

    # Hash functions used by the consistent hashing algorithms.
    # The list shows the currently implemented functions.
    # Benchmarks will run for every specified function.
    hash-functions:
        - xx

    # Statistical distributions of the keys.
    # At least one distribution must be provided.
    # Benchmarks will run for every specified key distribution.
    key-distributions:
    # - custom
    - uniform
    # - normal

# List of algorithms to be benchmarked. The list shows the currently implemented CH algorithms.
# If you add an algorithm called MyAlgo, the tool will search for a class named "MyAlgoFactory"
# that implements the ConsistentHashFactory interface. Every entry in the list must provide
# the algorithm name and an optional list of arguments to use during creation.
algorithms:
    # - name: anchor
    #   args:
    #       # The value is multiplied by the number of initial active nodes to find the capacity.
    #       # E.g., capacity=10 means that the overall capacity of the cluster is 10 times the initial number of working nodes.
    #       # Default value for the capacity is 10.
    #       capacity: 10
    # - name: binomial
            # No arguments
    - name: binomialnew
            # No arguments
    # - name: dx
    #   args: 
    #       # Same as above.
    #       capacity: 10
    # - name: jump
    #       # No arguments
    # - name: jumpback
          # No arguments
    # - name: memento
    #       # No arguments
    # - name: power
          # No arguments   


# Lists the benchmarks to be executed.
# The list shows the currently implemented benchmarks.
benchmarks: 

    # # Benchmarks the time needed by an algorithm to initialize its internal data structure.
    # - name: init-time
    #   # Can be used to override any common configuration.
    #   common:
    #   # Used to define any benchmark specific argument.
    #   args:

    # # Benchmarks the time needed to find which node a given key belongs.
    # - name: lookup-time
    #   # Can be used to override any common configuration.
    #   common:
    #   # Used to define any benchmark specific argument.
    #   args:
    #       # A number 0 <= x < 1 defining the percentage of initial nodes to remove
    #       # before performing the benchmark. This value defaults to 0
    #       # (The value cannot be 1 because 100% of the nodes cannot be removed).
    #       removal-rate: 0
    #       # Defines the order of nodes removal. Valid values for this property are:
    #       # FIFO, LIFO, and RANDOM. This value defaults to LIFO.
    #       # Note that not all the algorithms support any removal order.
    #       # For example Jump supports removals only in LIFO order.
    #       removal-order: lifo

    # Benchmarks the time needed by the algorithm to update its internal data structure when the cluster get resized.
    # - name: resize-time
    #   # Can be used to override any common configuration.
    #   common:
    #   # Used to define any benchmark specific argument.
    #   args:
    #       # A number 0 <= x < 1 defining the percentage of initial nodes to remove
    #       # before performing the benchmark. This value defaults to 0
    #       # (The value cannot be 1 because 100% of the nodes cannot be removed).
    #       removal-rate: 0.2
    #       # Defines the order of nodes removal. Valid values for this property are:
    #       # FIFO, LIFO, and RANDOM. This value defaults to LIFO.
    #       # Note that not all the algorithms support any removal order.
    #       # For example Jump supports removals only in LIFO order.
    #       removal-order: random      

    # Benchmarks the amount of RAM (in bytes) used by the algorithm.
    # - name: memory-usage
    #   # Can be used to override any common configuration.
    #   common:
    #   # Used to define any benchmark specific argument.
    #   args:
    #     # A number 0 <= x < 1 defining the percentage of initial nodes to remove
    #     # before performing the benchmark. This value defaults to 0
    #     # (The value cannot be 1 because 100% of the nodes cannot be removed).
    #     removal-rate: 0.2
    #     # Defines the order of nodes removal. Valid values for this property are:
    #     # FIFO, LIFO, and RANDOM. This value defaults to LIFO.
    #     # Note that not all the algorithms support any removal order.
    #     # For example Jump supports removals only in LIFO order.
    #     removal-order: random   

    # Benchmarks the distribution of the keys among the nodes of the cluster.
    - name: balance
      # Can be used to override any common configuration.
      common:
      # Used to define any benchmark specific argument.
      args:
        # A number 0 <= x < 1 defining the percentage of initial nodes to remove
        # before performing the benchmark. This value defaults to 0
        # (The value cannot be 1 because 100% of the nodes cannot be removed).
        removal-rate: 0
        # Defines the order of nodes removal. Valid values for this property are:
        # FIFO, LIFO, and RANDOM. This value defaults to LIFO.
        # Note that not all the algorithms support any removal order.
        # For example Jump supports removals only in LIFO order.
        removal-order: random 
        # The benchmark will be executed over a number of keys that is calculated by: keyMultiplier * cluster-nodes.
        # Default value is 100.
        key-multiplier: 1000
  
    # Benchmarks the distribution of the keys among the nodes of the cluster after a resize.
    # - name: resize-balance
    #   # Can be used to override any common configuration.
    #   common:
    #   # Used to define any benchmark specific argument.
    #   args:
    #       # See keyMultiplier on BenchmarkBalance.
    #       # Default value is 100.
    #       key-multiplier: 100 

    # Benchmarks the ability of the algorithm to move the minimal number of keys after a resize.
    # - name: monotonicity
    #   # Can be used to override any common configuration.
    #   common:
    #   # Used to define any benchmark specific argument.
    #   args:
    #     # A number 0 <= x < 1 defining the percentage of initial nodes to remove
    #     # before performing the benchmark. This value defaults to 0
    #     # (The value cannot be 1 because 100% of the nodes cannot be removed).
    #     removal-rate: 0
    #     # Defines the order of nodes removal. Valid values for this property are:
    #     # FIFO, LIFO, and RANDOM. This value defaults to LIFO.
    #     # Note that not all the algorithms support any removal order.
    #     # For example Jump supports removals only in LIFO order.
    #     removal-order: random 
    #     # See keyMultiplier on BenchmarkBalance.
    #     # Default value is 100.
    #     key-multiplier: 100
    #     # Percentage of nodes to remove. The provided value must be >= 0 and < 1).
    #     # At least one value must be provided.
    #     # The benchmark will run for every specified value.
    #     # fractions: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
    #     fractions: [.1,.2,.3,.4,.5]

    # Benchmarks the time needed to find which node a given key belongs.
    # This version keeps the cluster size fixed and incrementally removes the nodes.
    # - name: incremental-lookup-time
    #   # Can be used to override any common configuration.
    #   common:
    #   # Used to define any benchmark specific argument.
    #   # property with a fixed value.
    #     init-nodes: [1000]
    #   args:
    #     # Represents the persentage of nodes to remove.
    #     # Every value in the list must be a number 0 <= x < 1
    #     # defining the percentage of initial nodes to remove
    #     # before performing the benchmark.
    #     # This value defaults to [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
    #     # representing an incremental removal from 0% to 90% of the initial nodes.
    #     removal-rates: []

    # Benchmarks the amount of RAM (in bytes) used by the algorithm.
    # This version keeps the cluster size fixed and incrementally removes the nodes.
    # - name: incremental-memory-usage
    #   # Can be used to override any common configuration.
    #   common:
    #   # Used to define any benchmark specific argument.
    #     # property with a fixed value.
    #     init-nodes: [1000_000]
    #   args:
    #     # Represents the persentage of nodes to remove.
    #     # Every value in the list must be a number 0 <= x < 1
    #     # defining the percentage of initial nodes to remove
    #     # before performing the benchmark.
    #     # This value defaults to [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
    #     # representing an incremental removal from 0% to 90% of the initial nodes.
    #     removal-rates: []