# Configurations that will apply to every benchmark.
common:
    output-folder: /tmp

    iterations:
        warmup: 5
        run: 10

    init-nodes: [10, 100, 1000, 10000, 100000]

    hash-functions:
        - murmur3
        - crc32
        - md5
        - xx

algorithms:
    - name: anchor
    - name: dx
    - name: jump
    - name: maglev
    - name: memento
    - name: multi-probe
    - name: power
    - name: rendezvous
    - name: ring

benchmarks: 
    - name: init-time
    - name: lookup-time
      args:
          distributions:
            - uniform
            - normal
            - custom
    - name: resize-time
    - name: memory-usage
    - name: balance
    - name: resize-balance
    - name: monotonicity
      args:
          fractions: [0.1, 0.3, 0.5]
